<?php

namespace App\Support\AgentApi;

/**
 * What the REST contract says about each agent operation beyond its schemas:
 * method, path, scopes, prose, parameters, request and response schemas and
 * the responses it can answer with.
 *
 * {@see AgentOperations} turns each entry into the operation's REST binding,
 * and the registry generates `/api/openapi.json` from it. Schemas stay in the
 * components of `public/openapi/phr-agent-v1.json`, which is also the checked
 * copy of the generated document.
 */
final class AgentRestDocumentation
{
    /**
     * Scopes are null for a public operation and empty for one that needs any
     * credential. A request or response is a schema component name or an
     * inline schema; `success` maps each success status to its description;
     * `responses` maps every other status to a response component or object.
     *
     * @return array<string, array{method: string, path: string, summary: string, description: string|false, scopes: list<string>|null, parameters: list<string|array<string, mixed>>, request?: string|array<string, mixed>, request_types?: list<string>, request_required?: bool, success: array<int, string>, response?: string|array<string, mixed>, responses?: array<int|string, string|array<string, mixed>>}>
     */
    public static function operations(): array
    {
        return [
            'allergies.upsert' => [
                'method' => 'PUT',
                'path' => '/patients/{patient}/allergies',
                'summary' => 'Idempotently create or update an allergy',
                'description' => false,
                'scopes' => ['clinical:write'],
                'parameters' => ['PatientId'],
                'request' => 'AllergyUpsertRequest',
                'success' => [200 => 'Existing record updated or desired state already present', 201 => 'Record created'],
                'response' => 'ClinicalUpsertResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '409' => 'Conflict',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'capabilities.get' => [
                'method' => 'GET',
                'path' => '/capabilities',
                'summary' => 'Discover API operations, scopes, and limits',
                'description' => false,
                'scopes' => null,
                'parameters' => [],
                'success' => [200 => 'Server capabilities'],
                'response' => 'Capabilities',
                'responses' => ['429' => 'RateLimited'],
            ],
            'changes.list' => [
                'method' => 'GET',
                'path' => '/patients/{patient}/changes',
                'summary' => 'List bounded clinical changes using a stable snapshot watermark',
                'description' => 'Use the watermark returned by the first page for each following cursor page. Deleted and retracted resources are tombstones, never inferred from absence.',
                'scopes' => ['clinical:read'],
                'parameters' => ['PatientId', 'Limit', 'Cursor', 'ResourceTypes', 'UpdatedAfter', 'Watermark'],
                'success' => [200 => 'Stable cursor-bounded clinical change page'],
                'response' => 'ChangeFeedResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'clinical.get' => [
                'method' => 'GET',
                'path' => '/patients/{patient}/{resource}/{record}',
                'summary' => 'Get one core clinical record for an accessible patient',
                'description' => false,
                'scopes' => ['clinical:read'],
                'parameters' => ['PatientId', 'ClinicalResource', 'RecordId'],
                'success' => [200 => 'Clinical record'],
                'response' => 'ClinicalResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '429' => 'RateLimited',
                ],
            ],
            'clinical.list' => [
                'method' => 'GET',
                'path' => '/patients/{patient}/{resource}',
                'summary' => 'List one core clinical resource type for an accessible patient',
                'description' => false,
                'scopes' => ['clinical:read'],
                'parameters' => [
                    'PatientId',
                    'ClinicalResource',
                    'Limit',
                    'Cursor',
                    'UpdatedAfter',
                    'UpdatedBefore',
                    'ImportSource',
                    'SourceDocumentId',
                    'Archived',
                ],
                'success' => [200 => 'A cursor-bounded page of clinical records'],
                'response' => 'ClinicalListResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'clinical.resolve' => [
                'method' => 'POST',
                'path' => '/patients/{patient}/{resource}/resolve',
                'summary' => 'Resolve this connection\'s own external IDs to record identity and version',
                'description' => 'Maps a bounded batch of external IDs onto record IDs and current opaque versions for one writable clinical resource. Lookup is scoped to the calling OAuth client\'s own import source, so it answers whether this connection has written a record before and never discloses another integration\'s records or a browser-created record. No clinical content is returned, which is why clinical:read alone is sufficient. Call it before upserting to decide what still needs writing: a matching version means skip, a differing version means read the record first, and a rejected review_status means a human refused the record and it must not be re-asserted unchanged.',
                'scopes' => ['clinical:read'],
                'parameters' => ['PatientId', 'WritableClinicalResource'],
                'request' => 'ClinicalResolveRequest',
                'success' => [200 => 'Resolution of every requested external ID'],
                'response' => 'ClinicalResolveResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'clinical.retract' => [
                'method' => 'POST',
                'path' => '/patients/{patient}/{resource}/{record}/retract',
                'summary' => 'Withdraw a clinical record this connection wrote',
                'description' => 'Marks a record as withdrawn by the integration that wrote it. This means the source is taking back a claim it made in error; it does NOT mean the record is absent from a later export. Institutions age data out past their own retention policies, so absence from a newer import is never a reason to retract. Scope is this connection\'s own import namespace: a record written by another client, or created in the browser, reports 404 rather than 403, because refusing by name would confirm another integration holds that identifier. Nothing is deleted, the identity stays reserved so an ordinary upsert cannot re-assert it, and the record stops appearing in lists, search, timeline, and clinical exports. Retracting an already-retracted record is settled as unchanged.',
                'scopes' => ['clinical:write'],
                'parameters' => ['PatientId', 'WritableClinicalResource', 'RecordId'],
                'request' => 'ClinicalRetractionRequest',
                'success' => [200 => 'Record withdrawn, or already withdrawn'],
                'response' => 'ClinicalRetractionResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '409' => 'Conflict',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'clinical.update' => [
                'method' => 'PATCH',
                'path' => '/patients/{patient}/{resource}/{record}',
                'summary' => 'Partially update one existing writable clinical record',
                'description' => 'Read the record first and supply its current opaque version. Requires clinical:read as well as clinical:write. The update is patient-scoped and never changes import_source or external_id. Omitted fields are preserved; a supplied null source_document_id clears only that link. A stale or unknown version is rejected with 409 before anything is applied, and every effective change resets review_status to pending_review.',
                'scopes' => ['clinical:read', 'clinical:write'],
                'parameters' => ['PatientId', 'WritableClinicalResource', 'RecordId'],
                'request' => 'ClinicalRecordUpdateRequest',
                'success' => [200 => 'Record updated or desired state already present'],
                'response' => 'ClinicalUpsertResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '409' => 'Conflict',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'conditions.upsert' => [
                'method' => 'PUT',
                'path' => '/patients/{patient}/conditions',
                'summary' => 'Idempotently create or update a condition',
                'description' => false,
                'scopes' => ['clinical:write'],
                'parameters' => ['PatientId'],
                'request' => 'ConditionUpsertRequest',
                'success' => [200 => 'Existing record updated or desired state already present', 201 => 'Record created'],
                'response' => 'ClinicalUpsertResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '409' => 'Conflict',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'dicom_series.list' => [
                'method' => 'GET',
                'path' => '/patients/{patient}/dicom/studies/{study}/series',
                'summary' => 'List bounded DICOM series metadata',
                'description' => 'Returns series metadata and instance counts only; pixels, instance metadata, source paths, and object keys are never returned.',
                'scopes' => ['clinical:read'],
                'parameters' => [
                    'PatientId',
                    [
                        'name' => 'study',
                        'in' => 'path',
                        'required' => true,
                        'schema' => ['type' => 'integer', 'minimum' => 1],
                    ],
                    'Limit',
                    'Cursor',
                    'UpdatedAfter',
                    'UpdatedBefore',
                    [
                        'name' => 'modality',
                        'in' => 'query',
                        'schema' => ['type' => 'string', 'maxLength' => 16],
                    ],
                ],
                'success' => [200 => 'Bounded DICOM-series page'],
                'response' => 'DicomSeriesListResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'dicom_studies.get' => [
                'method' => 'GET',
                'path' => '/patients/{patient}/dicom/studies/{study}',
                'summary' => 'Get DICOM study metadata',
                'description' => false,
                'scopes' => ['clinical:read'],
                'parameters' => [
                    'PatientId',
                    [
                        'name' => 'study',
                        'in' => 'path',
                        'required' => true,
                        'schema' => ['type' => 'integer', 'minimum' => 1],
                    ],
                ],
                'success' => [200 => 'DICOM study metadata'],
                'response' => 'DicomStudyResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '429' => 'RateLimited',
                ],
            ],
            'dicom_studies.list' => [
                'method' => 'GET',
                'path' => '/patients/{patient}/dicom/studies',
                'summary' => 'List bounded DICOM study metadata',
                'description' => 'Returns study-level metadata and counts only; image pixels, instance metadata, storage keys, and files are never returned.',
                'scopes' => ['clinical:read'],
                'parameters' => [
                    'PatientId',
                    'Limit',
                    'Cursor',
                    'UpdatedAfter',
                    'UpdatedBefore',
                    [
                        'name' => 'modality',
                        'in' => 'query',
                        'schema' => ['type' => 'string', 'maxLength' => 16],
                    ],
                    'DateFrom',
                    'DateTo',
                ],
                'success' => [200 => 'Bounded DICOM-study page'],
                'response' => 'DicomStudyListResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'dicom_uploads.cancel' => [
                'method' => 'POST',
                'path' => '/patients/{patient}/dicom/uploads/{upload}/cancel',
                'summary' => 'Cancel an open DICOM upload session',
                'description' => false,
                'scopes' => ['clinical:write'],
                'parameters' => [
                    'PatientId',
                    [
                        'name' => 'upload',
                        'in' => 'path',
                        'required' => true,
                        'schema' => ['type' => 'integer', 'minimum' => 1],
                    ],
                ],
                'success' => [200 => 'Cancelled DICOM session'],
                'response' => 'DicomUploadCancelResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '429' => 'RateLimited',
                ],
            ],
            'dicom_uploads.finalize' => [
                'method' => 'POST',
                'path' => '/patients/{patient}/dicom/uploads/{upload}/finalize',
                'summary' => 'Finalize a DICOM upload session',
                'description' => false,
                'scopes' => ['clinical:write'],
                'parameters' => [
                    'PatientId',
                    [
                        'name' => 'upload',
                        'in' => 'path',
                        'required' => true,
                        'schema' => ['type' => 'integer', 'minimum' => 1],
                    ],
                ],
                'success' => [200 => 'Finalized DICOM session'],
                'response' => 'DicomUploadFinalizeResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'dicom_uploads.open' => [
                'method' => 'POST',
                'path' => '/patients/{patient}/dicom/uploads',
                'summary' => 'Open a DICOM upload session',
                'description' => false,
                'scopes' => ['clinical:write'],
                'parameters' => ['PatientId'],
                'request' => [
                    'type' => 'object',
                    'properties' => ['root_name' => ['type' => ['string', 'null'], 'maxLength' => 255]],
                    'additionalProperties' => false,
                ],
                'request_required' => false,
                'success' => [201 => 'Open DICOM upload session'],
                'response' => 'DicomUploadOpenResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'dicom_uploads.upload_file' => [
                'method' => 'POST',
                'path' => '/patients/{patient}/dicom/uploads/{upload}/files',
                'summary' => 'Upload one DICOM object to an open session',
                'description' => false,
                'scopes' => ['clinical:write'],
                'parameters' => [
                    'PatientId',
                    [
                        'name' => 'upload',
                        'in' => 'path',
                        'required' => true,
                        'schema' => ['type' => 'integer', 'minimum' => 1],
                    ],
                ],
                'request' => [
                    'type' => 'object',
                    'required' => ['file'],
                    'properties' => [
                        'file' => [
                            'type' => 'string',
                            'format' => 'binary',
                            'description' => 'One DICOM object, up to the advertised server limit.',
                        ],
                        'relative_path' => ['type' => ['string', 'null'], 'maxLength' => 1024],
                    ],
                    'additionalProperties' => false,
                ],
                'request_types' => ['multipart/form-data'],
                'success' => [200 => 'DICOM object stored or safely skipped'],
                'response' => 'DicomUploadFileResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '409' => 'Conflict',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'documents.download' => [
                'method' => 'GET',
                'path' => '/patients/{patient}/documents/{document}/file',
                'summary' => 'Download document bytes using OAuth plus an unexpired signature',
                'description' => false,
                'scopes' => ['documents:read'],
                'parameters' => [
                    'PatientId',
                    'DocumentId',
                    [
                        'name' => 'expires',
                        'in' => 'query',
                        'required' => true,
                        'schema' => ['type' => 'integer'],
                    ],
                    [
                        'name' => 'signature',
                        'in' => 'query',
                        'required' => true,
                        'schema' => ['type' => 'string'],
                    ],
                ],
                'success' => [200 => 'Document bytes'],
                'responses' => [
                    '200' => [
                        'description' => 'Document bytes',
                        'content' => [
                            'application/octet-stream' => ['schema' => ['type' => 'string', 'format' => 'binary']],
                        ],
                    ],
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '429' => 'RateLimited',
                ],
            ],
            'documents.download_access.create' => [
                'method' => 'POST',
                'path' => '/patients/{patient}/documents/{document}/download-access',
                'summary' => 'Create a one-minute signed download URL that still requires OAuth',
                'description' => false,
                'scopes' => ['documents:read'],
                'parameters' => ['PatientId', 'DocumentId'],
                'success' => [200 => 'Short-lived download access'],
                'response' => 'DownloadAccess',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '429' => 'RateLimited',
                ],
            ],
            'documents.get' => [
                'method' => 'GET',
                'path' => '/patients/{patient}/documents/{document}',
                'summary' => 'Get privacy-minimized document metadata',
                'description' => false,
                'scopes' => ['documents:read'],
                'parameters' => ['PatientId', 'DocumentId'],
                'success' => [200 => 'Document metadata'],
                'response' => 'DocumentResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '429' => 'RateLimited',
                ],
            ],
            'documents.list' => [
                'method' => 'GET',
                'path' => '/patients/{patient}/documents',
                'summary' => 'List privacy-minimized document metadata',
                'description' => false,
                'scopes' => ['documents:read'],
                'parameters' => [
                    'PatientId',
                    'Limit',
                    'Cursor',
                    'UpdatedAfter',
                    'UpdatedBefore',
                    'DateFrom',
                    'DateTo',
                    ['name' => 'document_type', 'in' => 'query', 'schema' => ['type' => 'string']],
                    ['name' => 'source', 'in' => 'query', 'schema' => ['type' => 'string']],
                    ['name' => 'tag', 'in' => 'query', 'schema' => ['type' => 'string', 'maxLength' => 100]],
                ],
                'success' => [200 => 'Bounded document page'],
                'response' => 'DocumentListResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'documents.upload' => [
                'method' => 'POST',
                'path' => '/patients/{patient}/documents',
                'summary' => 'Idempotently upload a patient document',
                'description' => 'The external identifier is namespaced to the OAuth client. Exact retries do not rewrite bytes, while changed bytes for the same identifier and same-client content-hash duplicates conflict.',
                'scopes' => ['documents:write'],
                'parameters' => ['PatientId'],
                'request' => 'DocumentUploadRequest',
                'request_types' => ['multipart/form-data'],
                'success' => [200 => 'Exact retry', 201 => 'Document created'],
                'response' => 'DocumentUploadResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '409' => 'Conflict',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'eob_lines.get' => [
                'method' => 'GET',
                'path' => '/patients/{patient}/eobs/{eob}/lines/{line}',
                'summary' => 'Get one EOB service line',
                'description' => false,
                'scopes' => ['clinical:read'],
                'parameters' => ['PatientId', 'EobId', 'LineId'],
                'success' => [200 => 'EOB line'],
                'response' => 'EobLineResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '429' => 'RateLimited',
                ],
            ],
            'eob_lines.list' => [
                'method' => 'GET',
                'path' => '/patients/{patient}/eobs/{eob}/lines',
                'summary' => 'List bounded EOB service lines without raw parser payloads',
                'description' => false,
                'scopes' => ['clinical:read'],
                'parameters' => ['PatientId', 'EobId', 'Limit', 'Cursor', 'UpdatedAfter', 'UpdatedBefore'],
                'success' => [200 => 'Bounded EOB-line page'],
                'response' => 'EobLineListResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'eobs.get' => [
                'method' => 'GET',
                'path' => '/patients/{patient}/eobs/{eob}',
                'summary' => 'Get one explanation-of-benefit record',
                'description' => false,
                'scopes' => ['clinical:read'],
                'parameters' => ['PatientId', 'EobId'],
                'success' => [200 => 'EOB'],
                'response' => 'EobResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '429' => 'RateLimited',
                ],
            ],
            'eobs.list' => [
                'method' => 'GET',
                'path' => '/patients/{patient}/eobs',
                'summary' => 'List explanation-of-benefit records without raw parser payloads',
                'description' => false,
                'scopes' => ['clinical:read'],
                'parameters' => [
                    'PatientId',
                    'Limit',
                    'Cursor',
                    'UpdatedAfter',
                    'UpdatedBefore',
                    'ImportSource',
                    'SourceDocumentId',
                    'DateFrom',
                    'DateTo',
                    [
                        'name' => 'claim_type',
                        'in' => 'query',
                        'schema' => ['type' => 'string', 'maxLength' => 30],
                    ],
                ],
                'success' => [200 => 'Bounded EOB page'],
                'response' => 'EobListResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'evidence.links' => [
                'method' => 'GET',
                'path' => '/patients/{patient}/evidence-links',
                'summary' => 'List typed evidence links from one patient-scoped record',
                'description' => false,
                'scopes' => ['clinical:read'],
                'parameters' => [
                    'PatientId',
                    [
                        'name' => 'resource_type',
                        'in' => 'query',
                        'required' => true,
                        'description' => 'Document sources additionally require documents:read; other sources require clinical:read only.',
                        'schema' => ['type' => 'string', 'enum' => ['document', 'eob', 'office-visit', 'procedure']],
                    ],
                    [
                        'name' => 'resource_id',
                        'in' => 'query',
                        'required' => true,
                        'schema' => ['type' => 'integer', 'minimum' => 1],
                    ],
                    'Limit',
                    'Cursor',
                ],
                'success' => [200 => 'Bounded evidence-link page'],
                'response' => 'EvidenceLinksResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'exports.create' => [
                'method' => 'POST',
                'path' => '/patients/{patient}/exports',
                'summary' => 'Queue a structured export',
                'description' => false,
                'scopes' => ['exports:write'],
                'parameters' => ['PatientId'],
                'request' => 'ExportCreateRequest',
                'request_required' => false,
                'success' => [202 => 'Export queued'],
                'response' => 'ExportMutationResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'exports.download_access.create' => [
                'method' => 'POST',
                'path' => '/patients/{patient}/exports/{export}/download-access',
                'summary' => 'Create short-lived export download access',
                'description' => false,
                'scopes' => ['exports:read'],
                'parameters' => ['PatientId', 'ExportId'],
                'success' => [200 => 'Bearer-authenticated temporary export URL'],
                'response' => 'ExportDownloadAccessResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '429' => 'RateLimited',
                ],
            ],
            'exports.list' => [
                'method' => 'GET',
                'path' => '/patients/{patient}/exports',
                'summary' => 'List bounded asynchronous export status',
                'description' => false,
                'scopes' => ['exports:read'],
                'parameters' => ['PatientId', 'Limit', 'Cursor', 'UpdatedAfter', 'UpdatedBefore'],
                'success' => [200 => 'Export status page'],
                'response' => 'ExportListResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'genai.attachments.download' => [
                'method' => 'GET',
                'path' => '/genai/requests/{requestId}/attachments/{attachmentId}',
                'summary' => 'Stream a leased health-document attachment with OAuth and signature',
                'description' => 'The temporary URL is not a bearer credential. The same genai:work OAuth Authorization header remains mandatory.',
                'scopes' => ['genai:work'],
                'parameters' => [
                    'GenAiRequestId',
                    'GenAiAttachmentId',
                    [
                        'name' => 'attempt',
                        'in' => 'query',
                        'required' => true,
                        'schema' => ['type' => 'integer', 'minimum' => 1],
                    ],
                    [
                        'name' => 'expires',
                        'in' => 'query',
                        'required' => true,
                        'schema' => ['type' => 'integer'],
                    ],
                    [
                        'name' => 'signature',
                        'in' => 'query',
                        'required' => true,
                        'schema' => ['type' => 'string'],
                    ],
                ],
                'success' => [200 => 'Streamed document bytes'],
                'responses' => [
                    '200' => [
                        'description' => 'Streamed document bytes',
                        'content' => [
                            'application/octet-stream' => ['schema' => ['type' => 'string', 'format' => 'binary']],
                        ],
                    ],
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '410' => 'NotFound',
                    '429' => 'RateLimited',
                ],
            ],
            'genai.leases.renew' => [
                'method' => 'POST',
                'path' => '/genai/requests/{requestId}/lease',
                'summary' => 'Renew an active external processing lease',
                'description' => false,
                'scopes' => ['genai:work'],
                'parameters' => ['GenAiRequestId'],
                'request' => 'GenAiLeaseRequest',
                'success' => [200 => 'Renewed lease'],
                'response' => 'GenAiClaimEnvelope',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '409' => 'Conflict',
                    '410' => 'Conflict',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'genai.queue_status' => [
                'method' => 'GET',
                'path' => '/genai/queue/status',
                'summary' => 'Read private external GenAI queue counts',
                'description' => false,
                'scopes' => ['genai:read'],
                'parameters' => [['name' => 'queue', 'in' => 'query', 'schema' => ['type' => 'string', 'maxLength' => 80]]],
                'success' => [200 => 'Bounded status counts'],
                'response' => 'GenAiQueueStatus',
                'responses' => ['401' => 'Unauthenticated', '403' => 'InsufficientScope', '429' => 'RateLimited'],
            ],
            'genai.requests.claim' => [
                'method' => 'POST',
                'path' => '/genai/claims',
                'summary' => 'Lease one authorized external GenAI request',
                'description' => false,
                'scopes' => ['genai:work'],
                'parameters' => [],
                'request' => [
                    'type' => 'object',
                    'properties' => ['queue' => ['type' => ['string', 'null'], 'maxLength' => 80]],
                    'additionalProperties' => false,
                ],
                'request_required' => false,
                'success' => [
                    200 => 'Lease, prompt, schemas, and authenticated attachment URLs',
                    204 => 'No currently claimable work',
                ],
                'response' => 'GenAiClaimEnvelope',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '409' => 'Conflict',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'genai.requests.complete' => [
                'method' => 'POST',
                'path' => '/genai/requests/{requestId}/complete',
                'summary' => 'Submit a schema-validated external completion',
                'description' => 'Completion commits durable delivery only; PHR reauthorizes and idempotently stages proposals for human review.',
                'scopes' => ['genai:work'],
                'parameters' => ['GenAiRequestId'],
                'request' => [
                    'type' => 'object',
                    'required' => ['lease_token', 'response'],
                    'properties' => [
                        'lease_token' => ['type' => 'string'],
                        'response' => ['type' => 'object'],
                        'executor' => ['type' => 'object', 'additionalProperties' => ['type' => 'string']],
                    ],
                    'additionalProperties' => false,
                ],
                'success' => [200 => 'Durable completion receipt'],
                'response' => ['type' => 'object', 'additionalProperties' => true],
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '409' => 'Conflict',
                    '410' => 'Conflict',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'genai.requests.fail' => [
                'method' => 'POST',
                'path' => '/genai/requests/{requestId}/fail',
                'summary' => 'Report a sanitized external processing failure',
                'description' => false,
                'scopes' => ['genai:work'],
                'parameters' => ['GenAiRequestId'],
                'request' => [
                    'type' => 'object',
                    'required' => ['lease_token', 'error', 'retryable'],
                    'properties' => [
                        'lease_token' => ['type' => 'string'],
                        'error' => [
                            'type' => 'object',
                            'required' => ['code', 'message'],
                            'properties' => [
                                'code' => ['type' => 'string', 'maxLength' => 80],
                                'message' => ['type' => 'string', 'maxLength' => 1000],
                            ],
                            'additionalProperties' => false,
                        ],
                        'retryable' => ['type' => 'boolean'],
                    ],
                    'additionalProperties' => false,
                ],
                'success' => [200 => 'Retry or terminal failure state'],
                'response' => ['type' => 'object', 'additionalProperties' => true],
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '409' => 'Conflict',
                    '410' => 'Conflict',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'genai.requests.get' => [
                'method' => 'GET',
                'path' => '/genai/requests/{requestId}',
                'summary' => 'Read one authorized external request status',
                'description' => false,
                'scopes' => ['genai:read'],
                'parameters' => ['GenAiRequestId'],
                'success' => [200 => 'Request status'],
                'response' => ['type' => 'object', 'additionalProperties' => true],
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '429' => 'RateLimited',
                ],
            ],
            'health_log_entries.append' => [
                'method' => 'POST',
                'path' => '/patients/{patient}/health-logs/{healthLog}/entries',
                'summary' => 'Idempotently append a health log entry',
                'description' => false,
                'scopes' => ['clinical:write'],
                'parameters' => ['PatientId', 'HealthLogId'],
                'request' => 'HealthLogEntryAppendRequest',
                'success' => [200 => 'Exact retry', 201 => 'Entry appended'],
                'response' => 'HealthLogEntryMutationResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '409' => 'Conflict',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'health_log_entries.get' => [
                'method' => 'GET',
                'path' => '/patients/{patient}/health-logs/{healthLog}/entries/{entry}',
                'summary' => 'Get one health log entry',
                'description' => false,
                'scopes' => ['clinical:read'],
                'parameters' => ['PatientId', 'HealthLogId', 'HealthLogEntryId'],
                'success' => [200 => 'Health log entry'],
                'response' => 'HealthLogEntryResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '429' => 'RateLimited',
                ],
            ],
            'health_log_entries.list' => [
                'method' => 'GET',
                'path' => '/patients/{patient}/health-logs/{healthLog}/entries',
                'summary' => 'List bounded entries for one health log',
                'description' => false,
                'scopes' => ['clinical:read'],
                'parameters' => [
                    'PatientId',
                    'HealthLogId',
                    'Limit',
                    'Cursor',
                    'UpdatedAfter',
                    'UpdatedBefore',
                    [
                        'name' => 'occurred_after',
                        'in' => 'query',
                        'schema' => ['type' => 'string', 'format' => 'date-time'],
                    ],
                    [
                        'name' => 'occurred_before',
                        'in' => 'query',
                        'schema' => ['type' => 'string', 'format' => 'date-time'],
                    ],
                ],
                'success' => [200 => 'Bounded health-log-entry page'],
                'response' => 'HealthLogEntryListResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'health_logs.create' => [
                'method' => 'POST',
                'path' => '/patients/{patient}/health-logs',
                'summary' => 'Idempotently create a patient health log',
                'description' => false,
                'scopes' => ['clinical:write'],
                'parameters' => ['PatientId'],
                'request' => 'HealthLogCreateRequest',
                'success' => [200 => 'Exact retry', 201 => 'Health log created'],
                'response' => 'HealthLogMutationResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '409' => 'Conflict',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'identity.get' => [
                'method' => 'GET',
                'path' => '/me',
                'summary' => 'Get the authorized identity and granted scopes',
                'description' => false,
                'scopes' => ['identity:read'],
                'parameters' => [],
                'success' => [200 => 'Authorized identity'],
                'response' => 'IdentityResponse',
                'responses' => ['401' => 'Unauthenticated', '403' => 'InsufficientScope', '429' => 'RateLimited'],
            ],
            'immunizations.upsert' => [
                'method' => 'PUT',
                'path' => '/patients/{patient}/immunizations',
                'summary' => 'Idempotently create or update an immunization',
                'description' => 'Stable external IDs are namespaced to the authenticated OAuth client. A changed existing record requires its current opaque version.',
                'scopes' => ['clinical:write'],
                'parameters' => ['PatientId'],
                'request' => 'ImmunizationUpsertRequest',
                'success' => [200 => 'Existing record updated or desired state already present', 201 => 'Record created'],
                'response' => 'ClinicalUpsertResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '409' => 'Conflict',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'imports.create' => [
                'method' => 'POST',
                'path' => '/patients/{patient}/imports',
                'summary' => 'Idempotently enqueue structured extraction for a stored document',
                'description' => false,
                'scopes' => ['imports:write'],
                'parameters' => ['PatientId'],
                'request' => 'ImportCreateRequest',
                'success' => [200 => 'The document already has an import job', 202 => 'Import job accepted'],
                'response' => 'ImportJobMutationResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '409' => 'Conflict',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'imports.get' => [
                'method' => 'GET',
                'path' => '/patients/{patient}/imports/{import}',
                'summary' => 'Inspect an import job and its proposed records',
                'description' => false,
                'scopes' => ['imports:read'],
                'parameters' => ['PatientId', 'ImportId'],
                'success' => [200 => 'Import job with proposals'],
                'response' => 'ImportJobResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '429' => 'RateLimited',
                ],
            ],
            'imports.list' => [
                'method' => 'GET',
                'path' => '/patients/{patient}/imports',
                'summary' => 'List structured import jobs',
                'description' => false,
                'scopes' => ['imports:read'],
                'parameters' => [
                    'PatientId',
                    'Limit',
                    'Cursor',
                    [
                        'name' => 'status',
                        'in' => 'query',
                        'schema' => ['$ref' => '#/components/schemas/ImportJobStatus'],
                    ],
                ],
                'success' => [200 => 'Bounded import-job page'],
                'response' => 'ImportJobListResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'imports.retry' => [
                'method' => 'POST',
                'path' => '/patients/{patient}/imports/{import}/retry',
                'summary' => 'Safely retry a failed import job',
                'description' => false,
                'scopes' => ['imports:write'],
                'parameters' => ['PatientId', 'ImportId'],
                'success' => [200 => 'The job is already queued or running', 202 => 'Retry accepted'],
                'response' => 'ImportJobMutationResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '409' => 'Conflict',
                    '429' => 'RateLimited',
                ],
            ],
            'imports.review' => [
                'method' => 'POST',
                'path' => '/patients/{patient}/imports/{import}/results/{result}/review',
                'summary' => 'Accept or reject one proposed import record',
                'description' => 'Write-only tokens receive a mutation-safe result receipt. Full extracted proposal data additionally requires imports:read.',
                'scopes' => ['imports:write'],
                'parameters' => ['PatientId', 'ImportId', 'ImportResultId'],
                'request' => 'ImportReviewRequest',
                'success' => [200 => 'Review applied or safely unchanged'],
                'response' => 'ImportReviewResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '409' => 'Conflict',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'lab_results.upsert' => [
                'method' => 'PUT',
                'path' => '/patients/{patient}/lab-results',
                'summary' => 'Idempotently create or update a lab result',
                'description' => false,
                'scopes' => ['clinical:write'],
                'parameters' => ['PatientId'],
                'request' => 'LabResultUpsertRequest',
                'success' => [200 => 'Existing record updated or desired state already present', 201 => 'Record created'],
                'response' => 'ClinicalUpsertResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '409' => 'Conflict',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'mcp.exchange' => [
                'method' => 'POST',
                'path' => '/mcp',
                'summary' => 'Exchange MCP Streamable HTTP JSON-RPC messages',
                'description' => 'MCP tools are thin adapters over the REST operations in this specification. Request bodies are limited to 262144 bytes. Tool calls additionally require each underlying REST operation\'s scope.',
                'scopes' => ['mcp:use'],
                'parameters' => [
                    [
                        'name' => 'Mcp-Session-Id',
                        'in' => 'header',
                        'required' => false,
                        'schema' => ['type' => 'string', 'format' => 'uuid'],
                    ],
                    [
                        'name' => 'Mcp-Protocol-Version',
                        'in' => 'header',
                        'required' => false,
                        'schema' => ['type' => 'string'],
                    ],
                ],
                'request' => [
                    'oneOf' => [
                        ['$ref' => '#/components/schemas/McpJsonRpcMessage'],
                        [
                            'type' => 'array',
                            'minItems' => 1,
                            'items' => ['$ref' => '#/components/schemas/McpJsonRpcMessage'],
                        ],
                    ],
                ],
                'success' => [200 => 'MCP JSON-RPC response or event stream', 202 => 'MCP notification accepted'],
                'responses' => [
                    '200' => [
                        'description' => 'MCP JSON-RPC response or event stream',
                        'headers' => ['Mcp-Session-Id' => ['schema' => ['type' => 'string', 'format' => 'uuid']]],
                        'content' => [
                            'application/json' => [
                                'schema' => [
                                    'oneOf' => [
                                        ['$ref' => '#/components/schemas/McpJsonRpcMessage'],
                                        [
                                            'type' => 'array',
                                            'items' => ['$ref' => '#/components/schemas/McpJsonRpcMessage'],
                                        ],
                                    ],
                                ],
                            ],
                            'text/event-stream' => ['schema' => ['type' => 'string']],
                        ],
                    ],
                    '400' => 'InvalidRequest',
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '413' => ['description' => 'MCP request body exceeds the configured size limit'],
                    '429' => 'RateLimited',
                ],
            ],
            'mcp.session.delete' => [
                'method' => 'DELETE',
                'path' => '/mcp',
                'summary' => 'End an MCP session',
                'description' => false,
                'scopes' => ['mcp:use'],
                'parameters' => [
                    [
                        'name' => 'Mcp-Session-Id',
                        'in' => 'header',
                        'required' => true,
                        'schema' => ['type' => 'string', 'format' => 'uuid'],
                    ],
                    [
                        'name' => 'Mcp-Protocol-Version',
                        'in' => 'header',
                        'required' => false,
                        'schema' => ['type' => 'string'],
                    ],
                ],
                'success' => [200 => 'MCP session ended'],
                'responses' => [
                    '400' => 'InvalidRequest',
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '429' => 'RateLimited',
                ],
            ],
            'medications.upsert' => [
                'method' => 'PUT',
                'path' => '/patients/{patient}/medications',
                'summary' => 'Idempotently create or update a medication',
                'description' => false,
                'scopes' => ['clinical:write'],
                'parameters' => ['PatientId'],
                'request' => 'MedicationUpsertRequest',
                'success' => [200 => 'Existing record updated or desired state already present', 201 => 'Record created'],
                'response' => 'ClinicalUpsertResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '409' => 'Conflict',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'native_backups.create' => [
                'method' => 'POST',
                'path' => '/patients/{patient}/native-backups',
                'summary' => 'Queue a native backup',
                'description' => false,
                'scopes' => ['exports:write'],
                'parameters' => ['PatientId'],
                'success' => [202 => 'Native backup queued'],
                'response' => 'NativeBackupMutationResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '429' => 'RateLimited',
                ],
            ],
            'native_backups.download_access.create' => [
                'method' => 'POST',
                'path' => '/patients/{patient}/native-backups/{backup}/download-access',
                'summary' => 'Create short-lived native-backup download access',
                'description' => false,
                'scopes' => ['exports:read'],
                'parameters' => ['PatientId', 'NativeBackupId'],
                'success' => [200 => 'Bearer-authenticated temporary native-backup URL'],
                'response' => 'NativeBackupDownloadAccessResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '429' => 'RateLimited',
                ],
            ],
            'native_backups.list' => [
                'method' => 'GET',
                'path' => '/patients/{patient}/native-backups',
                'summary' => 'List bounded asynchronous native-backup status',
                'description' => false,
                'scopes' => ['exports:read'],
                'parameters' => ['PatientId', 'Limit', 'Cursor', 'UpdatedAfter', 'UpdatedBefore'],
                'success' => [200 => 'Native-backup status page'],
                'response' => 'NativeBackupListResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'oauth.disconnect' => [
                'method' => 'DELETE',
                'path' => '/oauth/token',
                'summary' => 'Immediately revoke the current access token and its refresh token',
                'description' => false,
                'scopes' => [],
                'parameters' => [],
                'success' => [204 => 'Token family revoked'],
                'responses' => ['401' => 'Unauthenticated', '403' => 'InsufficientScope', '429' => 'RateLimited'],
            ],
            'office_visits.upsert' => [
                'method' => 'PUT',
                'path' => '/patients/{patient}/office-visits',
                'summary' => 'Idempotently create or update an office visit',
                'description' => 'Stable external IDs are namespaced to the authenticated OAuth client. A changed existing record requires its current opaque version; an already-applied retry remains safe with a stale version.',
                'scopes' => ['clinical:write'],
                'parameters' => ['PatientId'],
                'request' => 'OfficeVisitUpsertRequest',
                'success' => [200 => 'Existing record updated or desired state already present', 201 => 'Record created'],
                'response' => 'ClinicalUpsertResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '409' => 'Conflict',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'patients.create' => [
                'method' => 'POST',
                'path' => '/patients',
                'summary' => 'Create a new patient owned by the authorized user',
                'description' => false,
                'scopes' => ['patients:write'],
                'parameters' => [],
                'request' => 'PatientCreateRequest',
                'success' => [201 => 'Patient created'],
                'response' => 'PatientResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'patients.get' => [
                'method' => 'GET',
                'path' => '/patients/{patient}',
                'summary' => 'Get one accessible patient and the caller\'s access metadata',
                'description' => false,
                'scopes' => ['patients:read'],
                'parameters' => ['PatientId'],
                'success' => [200 => 'Accessible patient'],
                'response' => 'PatientResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '429' => 'RateLimited',
                ],
            ],
            'patients.list' => [
                'method' => 'GET',
                'path' => '/patients',
                'summary' => 'List patients accessible to the authorized user',
                'description' => false,
                'scopes' => ['patients:read'],
                'parameters' => ['Limit', 'Cursor', 'UpdatedAfter', 'UpdatedBefore', 'Archived'],
                'success' => [200 => 'A cursor-bounded page of accessible patients'],
                'response' => 'PatientListResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'procedures.upsert' => [
                'method' => 'PUT',
                'path' => '/patients/{patient}/procedures',
                'summary' => 'Idempotently create or update a procedure',
                'description' => 'Stable external IDs are namespaced to the authenticated OAuth client. A changed existing record requires its current opaque version; an already-applied retry remains safe with a stale version.',
                'scopes' => ['clinical:write'],
                'parameters' => ['PatientId'],
                'request' => 'ProcedureUpsertRequest',
                'success' => [200 => 'Existing record updated or desired state already present', 201 => 'Record created'],
                'response' => 'ClinicalUpsertResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '409' => 'Conflict',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'reconciliations.apply' => [
                'method' => 'POST',
                'path' => '/patients/{patient}/reconciliations/{reconciliation}/apply',
                'summary' => 'Apply an explicitly confirmed EOB reconciliation',
                'description' => 'The server recalculates the dry-run plan in its mutation transaction and rejects a stale preview digest.',
                'scopes' => ['reconciliation:write'],
                'parameters' => ['PatientId', 'Reconciliation'],
                'request' => 'ReconciliationApplyRequest',
                'success' => [200 => 'The exactly previewed reconciliation was applied'],
                'response' => 'ReconciliationApplyResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '409' => 'Conflict',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'reconciliations.preview' => [
                'method' => 'GET',
                'path' => '/patients/{patient}/reconciliations/{reconciliation}/preview',
                'summary' => 'Preview a privileged EOB reconciliation',
                'description' => 'Returns only the deterministic, count-based plan and confirmation digest; it never returns claim, provider, or record content.',
                'scopes' => ['reconciliation:read'],
                'parameters' => ['PatientId', 'Reconciliation'],
                'success' => [200 => 'Count-only reconciliation preview'],
                'response' => 'ReconciliationPreviewResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'records.search' => [
                'method' => 'GET',
                'path' => '/patients/{patient}/records/search',
                'summary' => 'Search concise records across core clinical resource types',
                'description' => false,
                'scopes' => ['clinical:read'],
                'parameters' => [
                    'PatientId',
                    'Limit',
                    'Cursor',
                    'ResourceTypes',
                    'SearchQuery',
                    'DateFrom',
                    'DateTo',
                    'Provider',
                    'Facility',
                    'Code',
                    'Source',
                    'ReviewStatus',
                    'UpdatedAfter',
                    'UpdatedBefore',
                ],
                'success' => [200 => 'A stable cursor-bounded cross-resource page'],
                'response' => 'RecordSearchResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'respiratory_events.ingest' => [
                'method' => 'POST',
                'path' => '/patients/{patient}/respiratory-events/batch',
                'summary' => 'Idempotently ingest a respiratory device event batch',
                'description' => 'Uses the same per-event validation and duplicate semantics as the Sinus Sentinel device endpoint.',
                'scopes' => ['clinical:write'],
                'parameters' => ['PatientId'],
                'request' => 'RespiratoryEventBatchRequest',
                'success' => [200 => 'Per-event accepted, duplicate, or rejected results'],
                'response' => 'RespiratoryEventBatchResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'respiratory_events.list' => [
                'method' => 'GET',
                'path' => '/patients/{patient}/respiratory-events',
                'summary' => 'List bounded respiratory device events',
                'description' => false,
                'scopes' => ['clinical:read'],
                'parameters' => [
                    'PatientId',
                    'Limit',
                    'Cursor',
                    'UpdatedAfter',
                    'UpdatedBefore',
                    [
                        'name' => 'occurred_after',
                        'in' => 'query',
                        'schema' => ['type' => 'string', 'format' => 'date-time'],
                    ],
                    [
                        'name' => 'occurred_before',
                        'in' => 'query',
                        'schema' => ['type' => 'string', 'format' => 'date-time'],
                    ],
                    [
                        'name' => 'event_type',
                        'in' => 'query',
                        'schema' => ['$ref' => '#/components/schemas/RespiratoryEventType'],
                    ],
                    [
                        'name' => 'include_false_positives',
                        'in' => 'query',
                        'schema' => ['type' => 'boolean', 'default' => false],
                    ],
                ],
                'success' => [200 => 'Bounded respiratory-event page'],
                'response' => 'RespiratoryEventListResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'timeline.list' => [
                'method' => 'GET',
                'path' => '/patients/{patient}/timeline',
                'summary' => 'List the patient timeline using the unified record projection',
                'description' => false,
                'scopes' => ['clinical:read'],
                'parameters' => [
                    'PatientId',
                    'Limit',
                    'Cursor',
                    'ResourceTypes',
                    'SearchQuery',
                    'DateFrom',
                    'DateTo',
                    'Provider',
                    'Facility',
                    'Code',
                    'Source',
                    'ReviewStatus',
                    'UpdatedAfter',
                    'UpdatedBefore',
                ],
                'success' => [200 => 'A stable cursor-bounded timeline page'],
                'response' => 'RecordSearchResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
            'vitals.upsert' => [
                'method' => 'PUT',
                'path' => '/patients/{patient}/vitals',
                'summary' => 'Idempotently create or update a vital',
                'description' => false,
                'scopes' => ['clinical:write'],
                'parameters' => ['PatientId'],
                'request' => 'VitalUpsertRequest',
                'success' => [200 => 'Existing record updated or desired state already present', 201 => 'Record created'],
                'response' => 'ClinicalUpsertResponse',
                'responses' => [
                    '401' => 'Unauthenticated',
                    '403' => 'InsufficientScope',
                    '404' => 'NotFound',
                    '409' => 'Conflict',
                    '422' => 'InvalidRequest',
                    '429' => 'RateLimited',
                ],
            ],
        ];
    }

    /**
     * Reusable parameters, under `components/parameters`.
     *
     * @return array<string, array<string, mixed>>
     */
    public static function parameters(): array
    {
        return [
            'PatientId' => [
                'name' => 'patient',
                'in' => 'path',
                'required' => true,
                'schema' => ['type' => 'integer', 'minimum' => 1],
            ],
            'RecordId' => [
                'name' => 'record',
                'in' => 'path',
                'required' => true,
                'schema' => ['type' => 'integer', 'minimum' => 1],
            ],
            'EobId' => [
                'name' => 'eob',
                'in' => 'path',
                'required' => true,
                'schema' => ['type' => 'integer', 'minimum' => 1],
            ],
            'LineId' => [
                'name' => 'line',
                'in' => 'path',
                'required' => true,
                'schema' => ['type' => 'integer', 'minimum' => 1],
            ],
            'DocumentId' => [
                'name' => 'document',
                'in' => 'path',
                'required' => true,
                'schema' => ['type' => 'integer', 'minimum' => 1],
            ],
            'ImportId' => [
                'name' => 'import',
                'in' => 'path',
                'required' => true,
                'schema' => ['type' => 'integer', 'minimum' => 1],
            ],
            'ImportResultId' => [
                'name' => 'result',
                'in' => 'path',
                'required' => true,
                'schema' => ['type' => 'integer', 'minimum' => 1],
            ],
            'GenAiRequestId' => [
                'name' => 'requestId',
                'in' => 'path',
                'required' => true,
                'schema' => ['type' => 'string', 'format' => 'uuid'],
            ],
            'GenAiAttachmentId' => [
                'name' => 'attachmentId',
                'in' => 'path',
                'required' => true,
                'schema' => ['type' => 'string', 'format' => 'uuid'],
            ],
            'ExportId' => [
                'name' => 'export',
                'in' => 'path',
                'required' => true,
                'schema' => ['type' => 'integer', 'minimum' => 1],
            ],
            'NativeBackupId' => [
                'name' => 'backup',
                'in' => 'path',
                'required' => true,
                'schema' => ['type' => 'integer', 'minimum' => 1],
            ],
            'HealthLogId' => [
                'name' => 'healthLog',
                'in' => 'path',
                'required' => true,
                'schema' => ['type' => 'integer', 'minimum' => 1],
            ],
            'HealthLogEntryId' => [
                'name' => 'entry',
                'in' => 'path',
                'required' => true,
                'schema' => ['type' => 'integer', 'minimum' => 1],
            ],
            'Reconciliation' => [
                'name' => 'reconciliation',
                'in' => 'path',
                'required' => true,
                'schema' => [
                    'type' => 'string',
                    'enum' => ['meritain-eob-visits', 'meritain-eob-allergy-procedures', 'delta-dental-eob-visits'],
                ],
            ],
            'ClinicalResource' => [
                'name' => 'resource',
                'in' => 'path',
                'required' => true,
                'schema' => [
                    'type' => 'string',
                    'enum' => [
                        'office-visits',
                        'procedures',
                        'immunizations',
                        'medications',
                        'conditions',
                        'allergies',
                        'lab-results',
                        'vitals',
                        'health-logs',
                    ],
                ],
            ],
            'WritableClinicalResource' => [
                'name' => 'resource',
                'in' => 'path',
                'required' => true,
                'schema' => [
                    'type' => 'string',
                    'enum' => [
                        'office-visits',
                        'procedures',
                        'immunizations',
                        'medications',
                        'conditions',
                        'allergies',
                        'lab-results',
                        'vitals',
                    ],
                ],
            ],
            'Limit' => [
                'name' => 'limit',
                'in' => 'query',
                'schema' => ['type' => 'integer', 'minimum' => 1, 'maximum' => 100, 'default' => 25],
            ],
            'Cursor' => ['name' => 'cursor', 'in' => 'query', 'schema' => ['type' => 'string', 'maxLength' => 2048]],
            'UpdatedAfter' => [
                'name' => 'updated_after',
                'in' => 'query',
                'schema' => ['type' => 'string', 'format' => 'date-time'],
            ],
            'UpdatedBefore' => [
                'name' => 'updated_before',
                'in' => 'query',
                'schema' => ['type' => 'string', 'format' => 'date-time'],
            ],
            'Watermark' => [
                'name' => 'watermark',
                'in' => 'query',
                'description' => 'Snapshot watermark returned by the first changes.list page; keep it unchanged while following cursors.',
                'schema' => ['type' => 'string', 'format' => 'date-time'],
            ],
            'ResourceTypes' => [
                'name' => 'resource_type[]',
                'in' => 'query',
                'style' => 'form',
                'explode' => true,
                'schema' => [
                    'type' => 'array',
                    'minItems' => 1,
                    'maxItems' => 9,
                    'uniqueItems' => true,
                    'items' => [
                        'type' => 'string',
                        'enum' => [
                            'office-visits',
                            'procedures',
                            'immunizations',
                            'medications',
                            'conditions',
                            'allergies',
                            'lab-results',
                            'vitals',
                            'health-logs',
                        ],
                    ],
                ],
            ],
            'SearchQuery' => ['name' => 'q', 'in' => 'query', 'schema' => ['type' => 'string', 'maxLength' => 200]],
            'DateFrom' => ['name' => 'date_from', 'in' => 'query', 'schema' => ['type' => 'string', 'format' => 'date']],
            'DateTo' => ['name' => 'date_to', 'in' => 'query', 'schema' => ['type' => 'string', 'format' => 'date']],
            'Provider' => ['name' => 'provider', 'in' => 'query', 'schema' => ['type' => 'string', 'maxLength' => 200]],
            'Facility' => ['name' => 'facility', 'in' => 'query', 'schema' => ['type' => 'string', 'maxLength' => 200]],
            'Code' => ['name' => 'code', 'in' => 'query', 'schema' => ['type' => 'string', 'maxLength' => 100]],
            'Source' => ['name' => 'source', 'in' => 'query', 'schema' => ['type' => 'string', 'maxLength' => 100]],
            'ReviewStatus' => [
                'name' => 'review_status',
                'in' => 'query',
                'description' => 'Matches the durable review_status field (pending_review, confirmed, rejected) across agent-reviewed clinical resources; condition/allergy verification_status remains a separate clinical field.',
                'schema' => ['type' => 'string', 'maxLength' => 50],
            ],
            'ImportSource' => [
                'name' => 'import_source',
                'in' => 'query',
                'description' => 'Exact provenance-source filter; prohibited for health logs.',
                'schema' => ['type' => 'string', 'maxLength' => 100],
            ],
            'SourceDocumentId' => [
                'name' => 'source_document_id',
                'in' => 'query',
                'description' => 'Exact source-document filter; prohibited for health logs.',
                'schema' => ['type' => 'integer', 'minimum' => 1],
            ],
            'Archived' => [
                'name' => 'archived',
                'in' => 'query',
                'description' => 'Patient and health-log archival filter. Prohibited for other clinical resources.',
                'schema' => ['type' => 'string', 'enum' => ['include', 'exclude', 'only'], 'default' => 'include'],
            ],
        ];
    }

    /**
     * Reusable responses, under `components/responses`.
     *
     * @return array<string, array<string, mixed>>
     */
    public static function responses(): array
    {
        return [
            'Unauthenticated' => [
                'description' => 'Missing, expired, or revoked bearer token',
                'content' => ['application/json' => ['schema' => ['$ref' => '#/components/schemas/Error']]],
            ],
            'InsufficientScope' => [
                'description' => 'The token does not grant the required scope',
                'content' => ['application/json' => ['schema' => ['$ref' => '#/components/schemas/Error']]],
            ],
            'RateLimited' => [
                'description' => 'Request or pre-authentication limit exceeded',
                'content' => ['application/json' => ['schema' => ['$ref' => '#/components/schemas/Error']]],
            ],
            'Conflict' => [
                'description' => 'The supplied stable identity conflicts with existing state, or a mutable record requires its current version',
                'content' => ['application/json' => ['schema' => ['$ref' => '#/components/schemas/Error']]],
            ],
            'NotFound' => [
                'description' => 'Patient, resource, or record was not found within the caller\'s access boundary',
                'content' => ['application/json' => ['schema' => ['$ref' => '#/components/schemas/Error']]],
            ],
            'InvalidRequest' => [
                'description' => 'A filter, limit, or cursor is invalid',
                'content' => ['application/json' => ['schema' => ['$ref' => '#/components/schemas/Error']]],
            ],
        ];
    }
}
